# Generated by Django 5.1.4 on 2025-01-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
